name: relecur
channels:
  - defaults
dependencies:
  - python==3.6.8
  - pip
  - pip:
    - gym==0.15.7
    - tensorflow==1.13.1
    - stable-baselines==2.10.2
    - scikit-surprise==1.1.1
    - ipykernel==5.5.5
    - numpy==1.14.6
    - pandas==0.24.2
    - turicreate==5.5
    - opencv-python==4.3.0.38
